import { StyleSheet } from "@react-pdf/renderer";

export const reportStyles = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 9,
    paddingTop: 42,
    paddingBottom: 42,
    paddingHorizontal: 36,
    color: "#202124",
  },
  cover: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  title: { fontSize: 26, fontWeight: 700, color: "#1a73e8" },
  subtitle: { fontSize: 15, marginTop: 10, fontWeight: 700 },
  coverMeta: { marginTop: 28, fontSize: 11, lineHeight: 1.5 },
  levelBadge: {
    marginTop: 24,
    paddingVertical: 10,
    paddingHorizontal: 22,
    backgroundColor: "#e8f0fe",
    border: "1 solid #1a73e8",
    borderRadius: 8,
    fontSize: 18,
    fontWeight: 700,
    color: "#154c91",
  },
  notice: { marginTop: 24, fontSize: 9, color: "#5f6368", maxWidth: 420 },
  assuranceNotice: {
    marginTop: 18,
    padding: 10,
    border: "1 solid #b3261e",
    backgroundColor: "#fce8e6",
    color: "#7a1b13",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
  },
  heading: {
    fontSize: 18,
    fontWeight: 700,
    color: "#154c91",
    marginBottom: 10,
  },
  subheading: {
    fontSize: 13,
    fontWeight: 700,
    color: "#1a73e8",
    marginTop: 12,
    marginBottom: 6,
  },
  label: { fontWeight: 700 },
  metadataRow: { flexDirection: "row", marginBottom: 5 },
  metadataLabel: { width: 125, fontWeight: 700 },
  metadataValue: { flex: 1 },
  summaryGrid: { flexDirection: "row", gap: 8, marginVertical: 12 },
  summaryCard: {
    flex: 1,
    padding: 8,
    border: "1 solid #dadce0",
    borderRadius: 4,
  },
  summaryValue: { fontSize: 15, fontWeight: 700, color: "#154c91" },
  summaryLabel: { fontSize: 8, color: "#5f6368", marginTop: 2 },
  gateGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 8,
  },
  gateCard: {
    width: "31.8%",
    minHeight: 76,
    padding: 7,
    border: "1 solid #dadce0",
    borderRadius: 4,
  },
  gateLevel: { fontSize: 7, fontWeight: 700, color: "#1a73e8" },
  gateName: { minHeight: 18, marginTop: 2, fontSize: 9, fontWeight: 700 },
  gateProgressTrack: {
    height: 5,
    marginTop: 5,
    backgroundColor: "#dadce0",
    borderRadius: 3,
    overflow: "hidden",
  },
  gateProgressValue: {
    height: 5,
    backgroundColor: "#1a73e8",
    borderRadius: 3,
  },
  gateStatus: { marginTop: 5, fontSize: 8, fontWeight: 700 },
  gateDetail: { marginTop: 1, fontSize: 7, color: "#5f6368" },
  item: {
    border: "1 solid #dadce0",
    borderRadius: 4,
    padding: 8,
    marginBottom: 7,
  },
  itemHeader: { flexDirection: "row", marginBottom: 4 },
  itemId: { width: 48, fontWeight: 700, color: "#154c91" },
  itemText: { flex: 1, fontWeight: 700 },
  status: { marginTop: 4, fontWeight: 700 },
  detail: { marginTop: 3 },
  muted: { color: "#5f6368" },
  pageNumber: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    textAlign: "center",
    fontSize: 8,
    color: "#80868b",
  },
});
