name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/')
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Build component
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm install
          npm run build
      - name: Copy index and data files
        run: |
          cp ./src/public/index.html ./dist/index.html
          cp ./src/public/assessment-data.yaml ./dist/assessment-data.yaml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
 
  # Deploy to GitHub pages
  deploy:
    needs: build
    permissions:
      pages: write 
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
