name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6
        with:
          node-version-file: ".node-version"
          registry-url: "https://npm.pkg.github.com"
          scope: "@pkic"
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
